package com.yourapp.USBooter.util

/**
 * Builds the `/usbooter/grub/grub.cfg` that the embedded GRUB core image runs on
 * legacy BIOS machines, from whatever the extracted image actually contains.
 *
 * Order of preference, which is what makes "most distros just boot":
 *  1. Windows install media -> chainload `bootmgr` through GRUB's ntldr module.
 *  2. The distro's own `/boot/grub/grub.cfg` -> `configfile`, so the user sees
 *     the exact menu the ISO author wrote (Ubuntu, Debian, Mint, Kali, ...).
 *  3. The distro's `isolinux.cfg`/`syslinux.cfg` -> `syslinux_configfile`, which
 *     GRUB translates on the fly (Fedora, CentOS, Alma, older Slackware, ...).
 *  4. A generated `linux`/`initrd` entry built from the kernel and initrd found
 *     in the tree, with the boot arguments the detected family needs.
 *
 * Every entry is emitted when its precondition holds, so if the first choice
 * fails at runtime the user can still pick the next one from the menu instead of
 * being dropped at a `grub>` prompt.
 */
object GrubConfigBuilder {

    private val DISTRO_GRUB_CONFIGS = listOf(
        "boot/grub/grub.cfg",
        "boot/grub2/grub.cfg",
        "efi/boot/grub.cfg"
    )

    private val ISOLINUX_CONFIGS = listOf(
        "isolinux/isolinux.cfg",
        "boot/isolinux/isolinux.cfg",
        "syslinux/syslinux.cfg",
        "boot/syslinux/syslinux.cfg"
    )

    private val KERNEL_PREFIXES = listOf("vmlinuz", "vmlinux", "bzimage", "kernel", "linux")
    private val INITRD_PREFIXES = listOf("initrd", "initramfs", "initrfs", "miniroot")

    /** One generated menu entry. */
    private data class Entry(val title: String, val body: String)

    fun build(
        entries: List<IsoEntry>,
        volumeLabel: String,
        isoDisplayName: String,
        /** Append the boot arguments that make the live image use the persistence volume. */
        persistence: Boolean = false
    ): String {
        val files = entries.filter { !it.isDirectory }.map { it.path.trimStart('/') }
        val lower = files.map { it.lowercase() }.toHashSet()
        val label = escape(volumeLabel.ifBlank { "USBOOTER" })
        val name = isoDisplayName.replace("\"", "").replace("$", "")

        val menu = mutableListOf<Entry>()

        if (lower.contains("bootmgr")) {
            menu += Entry(
                "Start $name (Windows setup, legacy BIOS)",
                "  insmod ntldr\n  ntldr /bootmgr"
            )
        }

        DISTRO_GRUB_CONFIGS.firstOrNull { lower.contains(it) }?.let { cfg ->
            menu += Entry(
                "Start $name (image's own GRUB menu)",
                "  configfile /$cfg"
            )
        }

        ISOLINUX_CONFIGS.filter { lower.contains(it) }.forEach { cfg ->
            menu += Entry(
                "Start $name (isolinux menu: /$cfg)",
                "  insmod syslinuxcfg\n  syslinux_configfile -i /$cfg"
            )
        }

        directBootEntries(files, label, name, persistence).forEach { menu += it }

        if (menu.isEmpty()) {
            menu += Entry(
                "No bootable configuration was detected - open a shell",
                "  echo \"This image has no BIOS bootloader that USBooter can drive.\"\n" +
                    "  echo \"Boot it in UEFI mode, or re-flash with raw image clone.\"\n  sleep 15"
            )
        }

        val sb = StringBuilder()
        sb.append("# Generated by USBooter - do not edit, it is rewritten on every flash.\n")
        sb.append("set timeout=10\nset default=0\nset pager=1\n")
        listOf(
            "part_msdos", "part_gpt", "fat", "exfat", "ntfs", "iso9660", "ext2",
            "search", "search_label", "search_fs_file", "linux", "linux16",
            "chain", "ntldr", "syslinuxcfg", "loopback", "all_video", "gzio"
        ).forEach { sb.append("insmod $it\n") }
        sb.append("if [ -z \"\$root\" ]; then\n")
        sb.append("  search --no-floppy --set=root --file /usbooter/grub/grub.cfg\n")
        sb.append("fi\n")
        sb.append("set USBOOTER_LABEL=\"$label\"\n\n")

        menu.forEach { entry ->
            sb.append("menuentry \"${entry.title}\" {\n")
            sb.append(entry.body).append("\n}\n\n")
        }

        sb.append("menuentry \"Reboot\" {\n  reboot\n}\n\n")
        sb.append("menuentry \"Power off\" {\n  halt\n}\n")
        return sb.toString()
    }

    /**
     * Builds `linux` + `initrd` entries directly from the kernels found in the
     * tree. The boot arguments differ per distro family because each one has its
     * own way of locating the root filesystem on the stick.
     */
    private fun directBootEntries(
        files: List<String>,
        label: String,
        name: String,
        persistence: Boolean
    ): List<Entry> {
        val kernels = files.filter { path ->
            val base = path.substringAfterLast('/').lowercase()
            KERNEL_PREFIXES.any { base.startsWith(it) } &&
                !base.endsWith(".efi") && !base.endsWith(".sig") && !base.endsWith(".txt")
        }.sortedBy { it.count { c -> c == '/' } }

        return kernels.take(3).mapNotNull { kernel ->
            val dir = kernel.substringBeforeLast('/', "")
            val initrd = files.firstOrNull { candidate ->
                candidate.substringBeforeLast('/', "") == dir &&
                    INITRD_PREFIXES.any { candidate.substringAfterLast('/').lowercase().startsWith(it) }
            } ?: files.firstOrNull { candidate ->
                INITRD_PREFIXES.any { candidate.substringAfterLast('/').lowercase().startsWith(it) }
            } ?: return@mapNotNull null

            val args = kernelArgs(dir.lowercase(), files, label, persistence)
            Entry(
                "Start $name (direct kernel: /$kernel)",
                "  linux /$kernel $args\n  initrd /$initrd"
            )
        }
    }

    /** Boot arguments per detected distro family. */
    private fun kernelArgs(
        dirLower: String,
        files: List<String>,
        label: String,
        persistence: Boolean = false
    ): String {
        val lower = files.map { it.lowercase() }
        val hasCasper = lower.any { it.startsWith("casper/") }
        val hasLive = lower.any { it.startsWith("live/") }
        val hasArch = lower.any { it.startsWith("arch/") }
        val hasFedoraLive = lower.any { it.startsWith("liveos/") || it.startsWith("images/") }
        val hasPuppySfs = lower.any { it.substringAfterLast('/').startsWith("puppy_") && it.endsWith(".sfs") }

        val persist = when {
            !persistence -> ""
            hasCasper || dirLower.startsWith("casper") -> " persistent"
            hasLive || dirLower.startsWith("live") -> " persistence"
            else -> ""
        }
        // Casper hands everything after "---" to the running system, not to the
        // initrd, so "persistent" has to be inserted *before* the separator or
        // Ubuntu-family images silently ignore the persistence volume.
        val raw = when {
            hasCasper || dirLower.startsWith("casper") ->
                "boot=casper ignore_uuid noprompt quiet splash$persist ---"
            hasLive || dirLower.startsWith("live") ->
                "boot=live components quiet splash$persist"
            hasArch || dirLower.startsWith("arch") ->
                "archisobasedir=arch archisolabel=$label"
            hasPuppySfs ->
                "pmedia=usbflash pfix=fsck"
            hasFedoraLive ->
                "root=live:LABEL=$label rd.live.image quiet"
            else ->
                "root=live:LABEL=$label rd.live.image boot=live quiet$persist"
        }
        return normalizeKernelArgs(raw)
    }

    /**
     * Makes a kernel command line syntactically valid before it ever reaches
     * GRUB: collapses repeated whitespace, drops characters GRUB would treat as
     * control tokens (newlines, `{`, `}`, `;`, quotes), removes duplicated
     * parameters keeping the first occurrence, escapes bare spaces inside a
     * value, and keeps the casper `---` separator last with everything that must
     * be seen by the initrd in front of it.
     */
    fun normalizeKernelArgs(raw: String): String {
        val cleaned = raw
            .replace(Regex("[\\r\\n\\t]+"), " ")
            .replace(Regex("[\"'{};]"), "")
            .trim()
        val tokens = cleaned.split(Regex("\\s+")).filter { it.isNotBlank() }
        val separator = tokens.contains("---")
        val seenKeys = LinkedHashSet<String>()
        val kept = mutableListOf<String>()
        tokens.filter { it != "---" }.forEach { token ->
            val key = token.substringBefore('=')
            if (key.isBlank()) return@forEach
            // A repeated key is a config bug: the kernel takes the last one, so
            // keeping the first and dropping the rest is the predictable choice.
            if (seenKeys.add(key)) kept.add(token)
        }
        if (separator) kept.add("---")
        return kept.joinToString(" ")
    }

    /**
     * The `/persistence.conf` Debian-live reads. Only `/ union` style mount
     * lines are valid; anything else is rejected so a malformed file can never
     * be written into the ext2 volume.
     */
    fun persistenceConf(family: String): String =
        if (family == "live") normalizePersistenceConf("/ union") else ""

    /**
     * Validates and normalizes a persistence.conf body: one mount point plus its
     * options per line, comments kept, blank lines dropped, LF line endings, a
     * trailing newline. Returns "" when nothing valid is left.
     */
    fun normalizePersistenceConf(raw: String): String {
        val lines = raw.replace("\r\n", "\n").replace('\r', '\n').split("\n")
        val out = mutableListOf<String>()
        val seenMounts = HashSet<String>()
        lines.forEach { line ->
            val trimmed = line.trim()
            if (trimmed.isEmpty()) return@forEach
            if (trimmed.startsWith("#")) { out.add(trimmed); return@forEach }
            val parts = trimmed.split(Regex("\\s+"))
            val mount = parts[0]
            // A mount point is an absolute path (or the special "/" union root).
            if (!mount.startsWith("/")) return@forEach
            if (!seenMounts.add(mount)) return@forEach
            val options = parts.drop(1)
                .filter { it.matches(Regex("[A-Za-z0-9_=,./+-]+")) }
                .distinct()
            out.add((listOf(mount) + options.ifEmpty { listOf("union") }).joinToString(" "))
        }
        return if (out.isEmpty()) "" else out.joinToString("\n") + "\n"
    }

    /**
     * What persistence will actually do, computed from the same code that
     * generates the menu, so the UI can show the exact kernel arguments and the
     * `/persistence.conf` contents before anything is written.
     *
     * Returns (kernelArgsWithPersistence, persistenceConfContents). The conf file
     * is only produced for the Debian-live family; casper finds its volume by
     * label alone and needs no file.
     */
    fun persistencePreview(
        entries: List<IsoEntry>,
        volumeLabel: String,
        family: String
    ): Pair<String, String> {
        val files = entries.filter { !it.isDirectory }.map { it.path.trimStart('/') }
        val label = escape(volumeLabel.ifBlank { "USBOOTER" })
        val dir = files.firstOrNull { path ->
            val base = path.substringAfterLast('/').lowercase()
            KERNEL_PREFIXES.any { base.startsWith(it) } && !base.endsWith(".efi")
        }?.substringBeforeLast('/', "")?.lowercase().orEmpty()
        val args = kernelArgs(dir, files, label, persistence = true)
        return args to persistenceConf(family)
    }

    /** GRUB parses spaces as argument separators, so escape them the GRUB way. */
    private fun escape(value: String): String =
        value.trim().replace("\\", "").replace("\"", "").replace(" ", "\\x20")
}

